name: Генерация YML-фида

on:
  schedule:
    - cron: '0 21 * * *'  # Каждый день в 21:00 МСК
  workflow_dispatch:     # Позволяет запускать вручную

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонировать репозиторий
        uses: actions/checkout@v4

      - name: 🐍 Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости
        run: |
          pip install requests beautifulsoup4 lxml

      - name: 🚀 Запустить скрипт
        run: |
          python feed/sushi.py

      - name: ✅ Проверить, создан ли фид
        run: |
          if [ -f "sushi_street_catalog.xml" ]; then
            echo "Фид успешно создан"
          else
            echo "❌ Ошибка: фид не создан"
            exit 1
          fi

      - name: 📤 Обновить фид в репозитории
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sushi_street_catalog.xml
          git commit -m "Обновлен фид: $(date)" || echo "Нет изменений"
          git push
