name: Генерация YML-фида

on:
  schedule:
    - cron: '0 21 * * *'  # Каждый день в 00:00 UTC
  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонировать репозиторий
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}  # ← Ключевая строка

      - name: 🐍 Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости
        run: |
          pip install requests beautifulsoup4 lxml

      - name: 🚀 Запустить скрипт
        run: |
          python sfeed.py

      - name: 🔍 Проверить, создан ли фид
        run: |
          if [ -f "sushi_street_catalog.xml" ]; then
            echo "✅ Фид создан, размер: $(wc -c < sushi_street_catalog.xml) байт"
          else
            echo "❌ Ошибка: фид не создан"
            ls -la
            exit 1
          fi

      - name: 📤 Загрузить обновления
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet sushi_street_catalog.xml; then
            echo "ℹ️ Фид не изменился — коммит не нужен"
            exit 0
          fi

          git add sushi_street_catalog.xml
          git commit -m "Обновлен фид: $(date)"
          git push  # Теперь push работает, потому что checkout был с токеном
          echo "✅ Фид обновлён и загружен"
