name: Генерация YML-фида

on:
  schedule:
    - cron: '0 21 * * *'  # Каждый день в 00:00 МСК
  workflow_dispatch:     # Позволяет запускать вручную

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонировать репозиторий
        uses: actions/checkout@v4

      - name: 🐍 Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости
        run: |
          pip install requests beautifulsoup4 lxml

      - name: 🚀 Запустить скрипт
        run: |
          python feed.py

      - name: 🔍 Проверить, создан ли фид
        run: |
          if [ -f "sushi_street_catalog.xml" ]; then
            echo "✅ Фид успешно создан: $(ls -la sushi_street_catalog.xml)"
            echo "Размер: $(wc -c < sushi_street_catalog.xml) байт"
          else
            echo "❌ Ошибка: фид не создан"
            ls -la  # Показать, что есть в папке
            exit 1
          fi

      - name: 📤 Обновить фид в репозитории
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet sushi_street_catalog.xml; then
            echo "ℹ️ Фид не изменился — коммит не нужен"
          else
            git add sushi_street_catalog.xml
            git commit -m "Обновлен фид: $(date)"
            git push
            echo "✅ Фид обновлён и загружен"
          fi
